name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  cancel_previous:

    runs-on: ubuntu-latest-large
    steps:
      - uses: styfle/cancel-workflow-action@a40b8845c0683271d9f53dfcb887a7e181d3918b  # 0.9.1
        with:
          workflow_id: ${{ github.event.workflow.id }}

  core-test:
    needs: cancel_previous
    runs-on: ubuntu-latest-large

    steps:
    - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5  # v4
    - name: Set up JDK 11
      uses: actions/setup-java@c1e323688fd81a25caa38c78aa6df2d33d3e20d9  # v4
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: cache gradle dependencies
      uses: actions/cache@6f8efc29b200d32929f49075959781ed54ec270c  # v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-core-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-core-
    - name: Run Tests
      run: ./gradlew core:test
    - name: Generate coverage report
      run: ./gradlew core:codeCoverageReport
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@f32b3a3741e1053eb607407145bc9619351dc93b  # v2

  android-test:
    needs: cancel_previous
    runs-on: ubuntu-latest-large

    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5  # v2
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: cache gradle dependencies
        uses: actions/cache@6f8efc29b200d32929f49075959781ed54ec270c  # v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-android-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-android-
      - name: Run Tests
        run: ./gradlew android:test
      - name: Generate coverage report
        run: ./gradlew android:codeCoverageReport
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@f32b3a3741e1053eb607407145bc9619351dc93b  # v2

  destination-test:
    needs: cancel_previous
    runs-on: ubuntu-latest-large

    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5  # v2
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: cache gradle dependencies
        uses: actions/cache@6f8efc29b200d32929f49075959781ed54ec270c  # v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-dest-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-dest-
      - name: Run Tests
        run: ./gradlew samples:kotlin-android-app-destinations:test
      - name: Generate coverage report
        run: ./gradlew samples:kotlin-android-app-destinations:codeCoverageReport
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@f32b3a3741e1053eb607407145bc9619351dc93b  # v2

  security:
    needs: cancel_previous
    runs-on: ubuntu-latest-large

    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5  # v2
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Snyk
        run: ./gradlew snyk-test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
